# Generated by Django 2.1.7 on 2019-04-17 08:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, null=True, verbose_name='Name')),
                ('Parish', models.CharField(max_length=120, null=True, verbose_name='Parish')),
                ('village', models.CharField(max_length=120, null=True, verbose_name='Village')),
                ('gender', models.CharField(choices=[('F', 'FEMALE'), ('M', 'MALE')], max_length=120, null=True, verbose_name='Gender')),
                ('birth_year', models.IntegerField(blank=True, null=True)),
                ('marriage', models.CharField(choices=[('S', 'SINGLE'), ('M', 'MARRIED')], max_length=120, null=True, verbose_name='Marriage status')),
                ('language', models.CharField(max_length=120, null=True, verbose_name='Language')),
                ('phone', models.CharField(max_length=120, null=True, verbose_name='Telephone')),
                ('photo', models.ImageField(blank=True, default='no-img.png', null=True, upload_to='')),
                ('community_status', models.CharField(max_length=120, null=True, verbose_name='Community status')),
                ('instructor_possibility', models.BooleanField(default=False)),
                ('farm_area', models.CharField(max_length=120, null=True, verbose_name='Farm Area')),
                ('crop_type', models.CharField(max_length=120, null=True, verbose_name='Crop type')),
                ('past_harvests', models.CharField(max_length=120, null=True, verbose_name='Past Harvests')),
                ('longitude', models.DecimalField(decimal_places=3, max_digits=8, null=True)),
                ('latitude', models.DecimalField(decimal_places=3, max_digits=8, null=True)),
                ('district_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='farm.District')),
            ],
        ),
        migrations.CreateModel(
            name='Harvest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('area', models.IntegerField(blank=True, null=True)),
                ('harvest', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, null=True)),
                ('login_id', models.CharField(max_length=120, null=True)),
                ('password', models.CharField(max_length=120, null=True)),
                ('phone', models.CharField(max_length=120, null=True)),
                ('district_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='farm.District')),
            ],
        ),
        migrations.CreateModel(
            name='Parish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=120, null=True)),
                ('rice_type', models.CharField(max_length=120, null=True)),
                ('sowing_date', models.DateField(blank=True, null=True)),
                ('sowing_type', models.CharField(max_length=120, null=True)),
                ('planting_type', models.CharField(max_length=120, null=True)),
                ('levelling', models.CharField(max_length=120, null=True)),
                ('ridge', models.CharField(max_length=120, null=True)),
                ('watercourse_state', models.CharField(max_length=120, null=True)),
                ('fertilizer', models.NullBooleanField()),
                ('fertilizer_1_type', models.CharField(max_length=120, null=True)),
                ('fertilizer_1_amount', models.IntegerField(blank=True, null=True)),
                ('fertilizer_2_type', models.CharField(max_length=120, null=True)),
                ('fertilizer_2_amount', models.IntegerField(blank=True, null=True)),
                ('weed_condition', models.CharField(max_length=120, null=True)),
                ('total_weed_times', models.IntegerField(blank=True, null=True)),
                ('harvest_date', models.DateField(blank=True, null=True)),
                ('harvest_amount', models.IntegerField(blank=True, null=True)),
                ('note', models.CharField(max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Subcounty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='farm.District')),
            ],
        ),
        migrations.AddField(
            model_name='report',
            name='season_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='farm.Season'),
        ),
        migrations.AddField(
            model_name='parish',
            name='subcounty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='farm.Subcounty'),
        ),
        migrations.AddField(
            model_name='officer',
            name='subcounty_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='farm.Subcounty'),
        ),
        migrations.AddField(
            model_name='harvest',
            name='season_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='farm.Season'),
        ),
        migrations.AddField(
            model_name='farmer',
            name='subcounty_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='farm.Subcounty'),
        ),
        migrations.AddField(
            model_name='farmer',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
