# Generated by Django 2.1.7 on 2019-04-10 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('farm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Harvest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('season', models.IntegerField(blank=True, null=True)),
                ('area', models.IntegerField(blank=True, null=True)),
                ('harvest', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_ptr',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='user',
        ),
        migrations.AddField(
            model_name='farmer',
            name='Parish',
            field=models.CharField(max_length=120, null=True, verbose_name='Parish'),
        ),
        migrations.AddField(
            model_name='farmer',
            name='birth_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farmer',
            name='community_status',
            field=models.CharField(max_length=120, null=True, verbose_name='Community status'),
        ),
        migrations.AddField(
            model_name='farmer',
            name='crop_type',
            field=models.CharField(max_length=120, null=True, verbose_name='Crop type'),
        ),
        migrations.AddField(
            model_name='farmer',
            name='district_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farmer',
            name='farm_area',
            field=models.CharField(max_length=120, null=True, verbose_name='Farm Area'),
        ),
        migrations.AddField(
            model_name='farmer',
            name='gender',
            field=models.CharField(max_length=120, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='farmer',
            name='instructor_possibility',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='farmer',
            name='language',
            field=models.CharField(max_length=120, null=True, verbose_name='Language'),
        ),
        migrations.AddField(
            model_name='farmer',
            name='latitude',
            field=models.DecimalField(decimal_places=3, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='farmer',
            name='longitude',
            field=models.DecimalField(decimal_places=3, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='farmer',
            name='marriage',
            field=models.CharField(max_length=120, null=True, verbose_name='Marriage status'),
        ),
        migrations.AddField(
            model_name='farmer',
            name='name',
            field=models.CharField(max_length=120, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='farmer',
            name='past_harvests',
            field=models.CharField(max_length=120, null=True, verbose_name='Past Harvests'),
        ),
        migrations.AddField(
            model_name='farmer',
            name='phone',
            field=models.CharField(max_length=120, null=True, verbose_name='Telephone'),
        ),
        migrations.AddField(
            model_name='farmer',
            name='photo',
            field=models.ImageField(blank=True, default='no-img.png', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='farmer',
            name='subcounty_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farmer',
            name='village',
            field=models.CharField(max_length=120, null=True, verbose_name='Village'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
