# Generated by Django 2.1.7 on 2019-04-10 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0003_farmer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmer',
            name='district_id',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='subcounty_id',
        ),
        migrations.AddField(
            model_name='farmer',
            name='district',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='farmer',
            name='subcounty',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
