# Generated by Django 2.1.7 on 2019-04-10 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0004_auto_20190410_1116'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.TextField(max_length=120, null=True)),
            ],
        ),
    ]
