# Generated by Django 2.1.7 on 2019-04-12 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0005_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, null=True)),
                ('login_id', models.CharField(max_length=120, null=True)),
                ('password', models.CharField(max_length=120, null=True)),
                ('phone', models.CharField(max_length=120, null=True)),
                ('district_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='farm.District')),
            ],
        ),
        migrations.CreateModel(
            name='Parish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Subcounty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='farm.District')),
            ],
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='district',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='subcounty',
        ),
        migrations.RemoveField(
            model_name='harvest',
            name='season',
        ),
        migrations.RemoveField(
            model_name='report',
            name='season',
        ),
        migrations.AddField(
            model_name='report',
            name='area',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='fertilizer',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='report',
            name='fertilizer_1_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='fertilizer_1_type',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='fertilizer_2_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='fertilizer_2_type',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='harvest_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='harvest_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='levelling',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='note',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='planting_type',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='rice_type',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='ridge',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='sowing_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='sowing_type',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='total_weed_times',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='watercourse_state',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='weed_condition',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='parish',
            name='subcounty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='farm.Subcounty'),
        ),
        migrations.AddField(
            model_name='officer',
            name='subcounty_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='farm.Subcounty'),
        ),
        migrations.AddField(
            model_name='farmer',
            name='district_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='farm.District'),
        ),
        migrations.AddField(
            model_name='farmer',
            name='subcounty_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='farm.Subcounty'),
        ),
        migrations.AddField(
            model_name='harvest',
            name='season_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='farm.Season'),
        ),
        migrations.AddField(
            model_name='report',
            name='season_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='farm.Season'),
        ),
    ]
